LOCAL:
    database:
        host: 'attsrabuni.ddns.net'
        db: 'AttsfTd'

# EN EL CONFIG DEBERIA IR TODO LO QUE ES CONFIGURABLE, PERO LOS DATOS REALES
# QUE VAYAN AL .ENV. EN EL CONFIG DEBERIAN IR LOS VALORES POR DEFECTO.
